### ISSUE TITLE
publish the actual app

### ISSUE THREAD

**Issue by tuxayo** [isa-group/governify#5]
None of the isa-group repo seems to be the code behind https://labs.isa.us.es:8181/IDEAS aka http://designer.governify.io

**Comment by antgamdia** [comment]
The code behind designer.governify.io is [isa-group/ideas-studio](https://github.com/isa-group/ideas-studio).

**Comment by tuxayo** [comment]
Thanks, sorry for having missed it an opened issues in the wrong repo.
