### ISSUE TITLE
Allow other browers than Chrome

### ISSUE THREAD

**Issue by tuxayo** [isa-group/governify#8]
Because the later it's done, the harder it might be. And having a webapp trapped on one browser is bad (remember the good old IE6 days).
- What are the Chrome only features being used?
- How do you check that the browser is Chrome/Chromium? On another browser I changed the user agent to match to the one of Chrome (and test if the app would still work) but it was not enough to pass the check.

**Comment by antgamdia** [comment]
We're working on analyzing the specific problems when using another browser. Thank you for your comments.

**Comment by feserafim** [comment]
Issue moved to [isa-group/ideas-studio #170](https://github.com/isa-group/ideas-studio/issues/170)
